
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-21T08:02:16-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "23441a0707484ff2e52d0c2a3d838bc8b530b86f",
 "version": "0.2.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
