import abc
from _typeshed import Incomplete
from abc import ABC
from proalgotrader_core.algo_session import AlgoSession as AlgoSession
from proalgotrader_core.api import Api as Api
from proalgotrader_core.broker_symbol import BrokerSymbol as BrokerSymbol
from proalgotrader_core.brokers.base_broker import BaseBroker as BaseBroker
from proalgotrader_core.order import Order as Order
from proalgotrader_core.protocols.enums.order_type import OrderType as OrderType
from proalgotrader_core.protocols.enums.position_type import PositionType as PositionType
from proalgotrader_core.protocols.enums.product_type import ProductType as ProductType
from proalgotrader_core.trade import Trade as Trade
from typing import Any, Dict

class PaperBroker(BaseBroker, ABC, metaclass=abc.ABCMeta):
    def __init__(self, api: Api, algo_session: AlgoSession) -> None: ...
    async def get_order_types(self) -> Dict[Any, Any]: ...
    async def get_position_types(self) -> Dict[Any, Any]: ...
    async def get_product_types(self) -> Dict[Any, Any]: ...
    initial_capital: Incomplete
    async def set_initial_capital(self) -> None: ...
    current_capital: Incomplete
    async def set_current_capital(self) -> None: ...
    async def get_current_capital(self): ...
    async def place_order(self, *, broker_symbol: BrokerSymbol, quantities: int, market_type: str, product_type: str, order_type: str, position_type: str, position_id: str | None) -> None: ...
    async def get_enter_position_info(self, order: Order, trade: Trade | None) -> Dict[str, Any]: ...
    async def get_exit_position_info(self, order: Order) -> Dict[str, Any]: ...
