from _typeshed import Incomplete
from sanmu import cmd as cmd

has_key: Incomplete
epilog: Incomplete

def sanmu() -> None: ...
def docs(*args, **kwargs): ...
def start(*args, **kwargs): ...
def report(*args, **kwargs): ...
def run(ctx, runner_args) -> None: ...
def register(key) -> None: ...
def main() -> None: ...
