from _typeshed import Incomplete
from collections.abc import Generator
from sanmu import sender as sender, settings as settings

logger: Incomplete
file_path: Incomplete

def verification_key(key: str = '', key_path: str = '.sanmu.key'): ...
def write_pytest_ini(func): ...
def switch_test_dir(target_path, allow_file: bool = False) -> Generator[None, None, None]: ...
def run(runner_args=(), plugins: Incomplete | None = None): ...
def report(s: bool = False, runner_args=(), plugins: Incomplete | None = None): ...
def docs(kw_type: str = 'all', *args, **kwargs) -> None: ...
def start(name, kw_type: str = 'all') -> None: ...
def main_with(path, *args, **kwargs): ...
