from _typeshed import Incomplete
from openpyxl.worksheet.worksheet import Worksheet as Worksheet

logger: Incomplete

class YamlFile(dict):
    def __init__(self, path) -> None: ...
    def load(self) -> None: ...
    def save(self) -> None: ...

class ExcelFile(YamlFile):
    def load(self) -> None: ...
    def save(self) -> None: ...
