import pytest
from _typeshed import Incomplete

logger: Incomplete

def pytest_configure(config: pytest.Config): ...
def pytest_terminal_summary(terminalreporter, *args, **kwargs) -> None: ...
def pytest_unconfigure(config: pytest.Config): ...
def pytest_collection_modifyitems(session, config, items) -> None: ...
