from _typeshed import Incomplete
from sanmu import cmd as cmd, settings as settings

logger: Incomplete
pool: Incomplete

def to_qywx(content: str): ...
def to_dingding(content: str): ...
def to_email(content: str): ...
def send_result(data: dict): ...
def send_report(url) -> None: ...
