# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cluster import *
from .get_cluster import *
from .get_clusters import *
from .get_instance import *
from .instance import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import ediri_akp.config as __config
    config = __config
else:
    config = _utilities.lazy_import('ediri_akp.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "akp",
  "mod": "index/cluster",
  "fqn": "ediri_akp",
  "classes": {
   "akp:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "akp",
  "mod": "index/instance",
  "fqn": "ediri_akp",
  "classes": {
   "akp:index/instance:Instance": "Instance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "akp",
  "token": "pulumi:providers:akp",
  "fqn": "ediri_akp",
  "class": "Provider"
 }
]
"""
)
