
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-25T09:54:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8a1a6a789c225f1f716049caa8bd8f95c8c0c3b",
 "version": "5.6.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
