# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general_classify_client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='general_classify_client.proto',
  package='vis.generalclassify',
  syntax='proto2',
  serialized_pb=_b('\n\x1dgeneral_classify_client.proto\x12\x13vis.generalclassify\"1\n\x0c\x43lassifyType\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x0e\n\x06topnum\x18\x02 \x01(\x05\"a\n\x16GeneralClassifyRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x38\n\rclassify_type\x18\x02 \x03(\x0b\x32!.vis.generalclassify.ClassifyType\"D\n\x08Location\x12\x0c\n\x04left\x18\x01 \x02(\x05\x12\x0b\n\x03top\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\"_\n\x06Object\x12\x0c\n\x04left\x18\x01 \x02(\x05\x12\x0b\n\x03top\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\x12\r\n\x05label\x18\x05 \x02(\x05\x12\x0c\n\x04prob\x18\x06 \x02(\x02\"\x82\x01\n\x0e\x43lassifyResult\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12/\n\x08location\x18\r \x01(\x0b\x32\x1d.vis.generalclassify.Location\x12,\n\x07objects\x18\x0e \x03(\x0b\x32\x1b.vis.generalclassify.Object\"N\n\x17GeneralClassifyResponse\x12\x33\n\x06result\x18\x01 \x03(\x0b\x32#.vis.generalclassify.ClassifyResultB\x03\x80\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLASSIFYTYPE = _descriptor.Descriptor(
  name='ClassifyType',
  full_name='vis.generalclassify.ClassifyType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_name', full_name='vis.generalclassify.ClassifyType.type_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topnum', full_name='vis.generalclassify.ClassifyType.topnum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=103,
)


_GENERALCLASSIFYREQUEST = _descriptor.Descriptor(
  name='GeneralClassifyRequest',
  full_name='vis.generalclassify.GeneralClassifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='vis.generalclassify.GeneralClassifyRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='classify_type', full_name='vis.generalclassify.GeneralClassifyRequest.classify_type', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=202,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='vis.generalclassify.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='vis.generalclassify.Location.left', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top', full_name='vis.generalclassify.Location.top', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='vis.generalclassify.Location.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='vis.generalclassify.Location.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=272,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='vis.generalclassify.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='vis.generalclassify.Object.left', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top', full_name='vis.generalclassify.Object.top', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='vis.generalclassify.Object.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='vis.generalclassify.Object.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='vis.generalclassify.Object.label', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='vis.generalclassify.Object.prob', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=369,
)


_CLASSIFYRESULT = _descriptor.Descriptor(
  name='ClassifyResult',
  full_name='vis.generalclassify.ClassifyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_name', full_name='vis.generalclassify.ClassifyResult.type_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='vis.generalclassify.ClassifyResult.location', index=1,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='objects', full_name='vis.generalclassify.ClassifyResult.objects', index=2,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=502,
)


_GENERALCLASSIFYRESPONSE = _descriptor.Descriptor(
  name='GeneralClassifyResponse',
  full_name='vis.generalclassify.GeneralClassifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='vis.generalclassify.GeneralClassifyResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=582,
)

_GENERALCLASSIFYREQUEST.fields_by_name['classify_type'].message_type = _CLASSIFYTYPE
_CLASSIFYRESULT.fields_by_name['location'].message_type = _LOCATION
_CLASSIFYRESULT.fields_by_name['objects'].message_type = _OBJECT
_GENERALCLASSIFYRESPONSE.fields_by_name['result'].message_type = _CLASSIFYRESULT
DESCRIPTOR.message_types_by_name['ClassifyType'] = _CLASSIFYTYPE
DESCRIPTOR.message_types_by_name['GeneralClassifyRequest'] = _GENERALCLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['ClassifyResult'] = _CLASSIFYRESULT
DESCRIPTOR.message_types_by_name['GeneralClassifyResponse'] = _GENERALCLASSIFYRESPONSE

ClassifyType = _reflection.GeneratedProtocolMessageType('ClassifyType', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYTYPE,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.ClassifyType)
  ))
_sym_db.RegisterMessage(ClassifyType)

GeneralClassifyRequest = _reflection.GeneratedProtocolMessageType('GeneralClassifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERALCLASSIFYREQUEST,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.GeneralClassifyRequest)
  ))
_sym_db.RegisterMessage(GeneralClassifyRequest)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.Location)
  ))
_sym_db.RegisterMessage(Location)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
  DESCRIPTOR = _OBJECT,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.Object)
  ))
_sym_db.RegisterMessage(Object)

ClassifyResult = _reflection.GeneratedProtocolMessageType('ClassifyResult', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESULT,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.ClassifyResult)
  ))
_sym_db.RegisterMessage(ClassifyResult)

GeneralClassifyResponse = _reflection.GeneratedProtocolMessageType('GeneralClassifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERALCLASSIFYRESPONSE,
  __module__ = 'general_classify_client_pb2'
  # @@protoc_insertion_point(class_scope:vis.generalclassify.GeneralClassifyResponse)
  ))
_sym_db.RegisterMessage(GeneralClassifyResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
