# SPDX-License-Identifier: LGPL-2.1-or-later

from os.path import join

DIRECTORY_RAW_DATA = "raw"
DIRECTORY_SBOM_DATA = "sboms"

DIRECTORY_NAME_SBOM_SPDX = "spdx"
DIRECTORY_NAME_SBOM_CYCLONEDX = "cyclonedx"

FILE_NAME_REQUIRED_RPMS = "required_rpms"
FILE_PATH_REQUIRED_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_REQUIRED_RPMS)

FILE_NAME_REQUIRED_BY_RPMS = "required_by_rpms"
FILE_PATH_REQUIRED_BY_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_REQUIRED_BY_RPMS)

FILE_NAME_RECOMMENDED_BY_RPMS = "recommended_by_rpms"
FILE_PATH_RECOMMENDED_BY_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_RECOMMENDED_BY_RPMS)

FILE_NAME_ROOT_RPMS = "root_rpms"
FILE_PATH_ROOT_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_ROOT_RPMS)

FILE_NAME_ALL_RPMS = "all_rpms"
FILE_PATH_ALL_RPMS = join(DIRECTORY_RAW_DATA, FILE_NAME_ALL_RPMS)

FILE_SBOM_TEMPLATE_ROOT = "document.tmpl"

FILE_NAME_GIT_SUBMODULES = "git_submodules"
FILE_PATH_GIT_SUBMODULES = join(DIRECTORY_RAW_DATA, FILE_NAME_GIT_SUBMODULES)

SUPPORTED_SBOM_FORMATS = [DIRECTORY_NAME_SBOM_SPDX, DIRECTORY_NAME_SBOM_CYCLONEDX]
