
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-23T14:41:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e73e0d6c38c816e298286c99a780f6b0bc92a773",
 "version": "6.25.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
