
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-22T12:28:35-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "be7496f4a8bdfd64266ff234c5dadf496accf666",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
