# - create_user(user_data)
# - create_personal_access_token(user_name)
# - delete_user(user_name)
# - list_personal_access_tokens(user_name)
# - list_users()
# - modify_user(user_name, **kwargs)
# - read_user(user_name)
# - revoke_personal_access_token(user_name, token_id)