# Generated by Django 5.0.3 on 2024-03-20 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_title', models.CharField(default='휴진안내', help_text='줄넘기기 : \\n', max_length=40, verbose_name='calendar_name')),
                ('activate', models.BooleanField(default=False, help_text='활성창 1개만 가능')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='휴진', max_length=20, verbose_name='title')),
                ('date_of_event', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar', to='django_calendards.calendar')),
            ],
        ),
    ]
