# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20076_message import InlineResponse20076Message  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20076Message(unittest.TestCase):
    """InlineResponse20076Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20076Message(self):
        """Test InlineResponse20076Message"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20076_message.InlineResponse20076Message()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
