# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20096_raid_groups_raid_group import InlineResponse20096RaidGroupsRaidGroup  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20096RaidGroupsRaidGroup(unittest.TestCase):
    """InlineResponse20096RaidGroupsRaidGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20096RaidGroupsRaidGroup(self):
        """Test InlineResponse20096RaidGroupsRaidGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20096_raid_groups_raid_group.InlineResponse20096RaidGroupsRaidGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
