# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200126_fault_domains import InlineResponse200126FaultDomains  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200126FaultDomains(unittest.TestCase):
    """InlineResponse200126FaultDomains unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200126FaultDomains(self):
        """Test InlineResponse200126FaultDomains"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200126_fault_domains.InlineResponse200126FaultDomains()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
