# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03-sp1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20080_message_param import InlineResponse20080MessageParam  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20080MessageParam(unittest.TestCase):
    """InlineResponse20080MessageParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20080MessageParam(self):
        """Test InlineResponse20080MessageParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20080_message_param.InlineResponse20080MessageParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
