
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-22T18:01:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "be4b485322b1be52f78dfe6d03694d6ba2000b11",
 "version": "1.0.0.post0.dev180"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
