# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _proto/commander/service/v2/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n)_proto/commander/service/v2/service.proto\x12\x1b_proto.commander.service.v2"B\n\x17\x43reateImportPlanRequest\x12\x15\n\rsearch_string\x18\x01 \x01(\t\x12\x10\n\x08max_rows\x18\x02 \x01(\x03"*\n\x18\x43reateImportPlanResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t"J\n\x16\x41pplyImportPlanRequest\x12\x11\n\tplan_yaml\x18\x01 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t")\n\x17\x41pplyImportPlanResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t2\x98\x02\n\x12V2CommanderService\x12\x81\x01\n\x10\x43reateImportPlan\x12\x34._proto.commander.service.v2.CreateImportPlanRequest\x1a\x35._proto.commander.service.v2.CreateImportPlanResponse"\x00\x12~\n\x0f\x41pplyImportPlan\x12\x33._proto.commander.service.v2.ApplyImportPlanRequest\x1a\x34._proto.commander.service.v2.ApplyImportPlanResponse"\x00\x42-Z+github.com/BauplanLabs/commander/service/v2b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_proto.commander.service.v2.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/BauplanLabs/commander/service/v2'
    _globals['_CREATEIMPORTPLANREQUEST']._serialized_start = 74
    _globals['_CREATEIMPORTPLANREQUEST']._serialized_end = 140
    _globals['_CREATEIMPORTPLANRESPONSE']._serialized_start = 142
    _globals['_CREATEIMPORTPLANRESPONSE']._serialized_end = 184
    _globals['_APPLYIMPORTPLANREQUEST']._serialized_start = 186
    _globals['_APPLYIMPORTPLANREQUEST']._serialized_end = 260
    _globals['_APPLYIMPORTPLANRESPONSE']._serialized_start = 262
    _globals['_APPLYIMPORTPLANRESPONSE']._serialized_end = 303
    _globals['_V2COMMANDERSERVICE']._serialized_start = 306
    _globals['_V2COMMANDERSERVICE']._serialized_end = 586
# @@protoc_insertion_point(module_scope)
