
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-23T11:46:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "56a783955d53fd40500e5d1c1b618d0859cebed8",
 "version": "6.25.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
