import abc
from _typeshed import Incomplete
from abc import abstractmethod

class BaseTokenManager(metaclass=abc.ABCMeta):
    file_name: Incomplete
    logs_path: Incomplete
    data_path: Incomplete
    def __init__(self) -> None: ...
    def set_access_token_file_name(self, path_name: str, unique_id: str) -> None: ...
    @abstractmethod
    def get_token(self) -> str: ...
    @abstractmethod
    def set_token(self, token: str) -> None: ...
    def initialize(self) -> None: ...
