"""Provide the VotableMixin class."""

from __future__ import annotations

class VotableMixin:
    async def _vote(self, direction: int) -> None: ...
    async def clear_vote(self) -> None: ...
    async def downvote(self) -> None: ...
    async def upvote(self) -> None: ...
