# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: acp_add_notification.proto, acp_del_notification.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

import enumdef


@dataclass
class AddNotificationRequest(betterproto.Message):
    id_group: int = betterproto.uint64_field(1)
    offset: int = betterproto.uint32_field(2)
    length: int = betterproto.uint32_field(3)
    max_delay: int = betterproto.uint32_field(4)
    cycle_time: int = betterproto.uint32_field(5)
    data: bytes = betterproto.bytes_field(6)


@dataclass
class AddNotificationResponse(betterproto.Message):
    result: enumdef.Errors = betterproto.enum_field(1)
    handle: int = betterproto.uint64_field(2)
    data: bytes = betterproto.bytes_field(3)


@dataclass
class DeleteNotificationRequest(betterproto.Message):
    handle: int = betterproto.uint64_field(1)


@dataclass
class DeleteNotificationResponse(betterproto.Message):
    result: enumdef.Errors = betterproto.enum_field(1)
