# Generated by Django 3.1.7 on 2021-03-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statistic.period'),
        ),
    ]
