#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2402-41-geef79e64"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2402
#define NETGEN_VERSION_TWEAK 41
#define NETGEN_VERSION_HASH "geef79e64"
#endif // NETGEN_VERSION_HPP_INCLUDED
