"""The table module for the pyformance analytics code."""
# ruff: noqa: F401
from .annualized_returns import AnnualizedReturns
from .arbitrary import Arbitrary
from .arbitrary_metrics import ArbitraryMetrics
from .autocorrelation import Autocorrelation
from .calendar_returns import CalendarReturns
from .capture_ratios import CaptureRatios
from .correlation import Correlation
from .distributions import Distributions
from .downside_risk import DownsideRisk
from .downside_risk_ratio import DownsideRiskRatio
from .drawdowns import Drawdowns
from .drawdowns_ratio import DrawdownsRatio
from .higher_moments import HigherMoments
from .information_ratio import InformationRatio
from .prob_out_performance import ProbOutPerformance
from .rolling_periods import RollingPeriods
from .SFM import SFM
from .specific_risk import SpecificRisk
from .stats import Stats
from .trailing_periods_rel import TrailingPeriodsRel
from .up_down_ratios import UpDownRatios
from .variability import Variability
