# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/SessionController/SessionServices.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openobd_protocol import Status_pb2 as openobd__protocol_dot_Status__pb2
from openobd_protocol.SessionController import Session_pb2 as openobd__protocol_dot_SessionController_dot_Session__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8openobd_protocol/SessionController/SessionServices.proto\x12/com.jifeline.OpenOBD.Protocol.SessionController\x1a\x1dopenobd_protocol/Status.proto\x1a\x30openobd_protocol/SessionController/Session.proto2\xa4\x04\n\x0fSessionServices\x12\x61\n\x0fgetSessionToken\x12%.com.jifeline.OpenOBD.Protocol.Status\x1a%.com.jifeline.OpenOBD.Protocol.Status\"\x00\x12\x8e\x01\n\rcreateSession\x12=.com.jifeline.OpenOBD.Protocol.SessionController.startSession\x1a<.com.jifeline.OpenOBD.Protocol.SessionController.sessionInfo\"\x00\x12\\\n\ngetSession\x12%.com.jifeline.OpenOBD.Protocol.Status\x1a%.com.jifeline.OpenOBD.Protocol.Status\"\x00\x12_\n\rdeleteSession\x12%.com.jifeline.OpenOBD.Protocol.Status\x1a%.com.jifeline.OpenOBD.Protocol.Status\"\x00\x12^\n\x0clistSessions\x12%.com.jifeline.OpenOBD.Protocol.Status\x1a%.com.jifeline.OpenOBD.Protocol.Status\"\x00\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.SessionController.SessionServices_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_SESSIONSERVICES']._serialized_start=191
  _globals['_SESSIONSERVICES']._serialized_end=739
# @@protoc_insertion_point(module_scope)
