depends = ('ITKPyBase', 'ITKTransform', 'ITKImageFrequency', 'ITKIOImageBase', 'ITKFFT', 'ITKCommon', )
templates = (  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorF2', True, 'float, 2'),
  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorD2', True, 'double, 2'),
  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorF3', True, 'float, 3'),
  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorD3', True, 'double, 3'),
  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorF4', True, 'float, 4'),
  ('PhaseCorrelationOperator', 'itk::PhaseCorrelationOperator', 'itkPhaseCorrelationOperatorD4', True, 'double, 4'),
  ('PhaseCorrelationOptimizerEnums', 'itk::PhaseCorrelationOptimizerEnums', 'itkPhaseCorrelationOptimizerEnums', False),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerF2', True, 'float, 2'),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerD2', True, 'double, 2'),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerF3', True, 'float, 3'),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerD3', True, 'double, 3'),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerF4', True, 'float, 4'),
  ('PhaseCorrelationOptimizer', 'itk::PhaseCorrelationOptimizer', 'itkPhaseCorrelationOptimizerD4', True, 'double, 4'),
  ('PhaseCorrelationImageRegistrationMethodEnums', 'itk::PhaseCorrelationImageRegistrationMethodEnums', 'itkPhaseCorrelationImageRegistrationMethodEnums', False),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUS2IUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodID2ID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUS3IUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodID3ID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodISS4ISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUC4IUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIUS4IUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >'),
  ('PhaseCorrelationImageRegistrationMethod', 'itk::PhaseCorrelationImageRegistrationMethod', 'itkPhaseCorrelationImageRegistrationMethodID4ID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTTD2', False, 'itk::TranslationTransform< double , 2 >'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTTD3', False, 'itk::TranslationTransform< double , 3 >'),
  ('DataObjectDecorator', 'itk::DataObjectDecorator', 'itkDataObjectDecoratorTTD4', False, 'itk::TranslationTransform< double , 4 >'),
  ('SimpleDataObjectDecorator', 'itk::SimpleDataObjectDecorator', 'itkSimpleDataObjectDecoratorPD2', False, 'itk::Point< double , 2 >'),
  ('SimpleDataObjectDecorator', 'itk::SimpleDataObjectDecorator', 'itkSimpleDataObjectDecoratorPD3', False, 'itk::Point< double , 3 >'),
  ('SimpleDataObjectDecorator', 'itk::SimpleDataObjectDecorator', 'itkSimpleDataObjectDecoratorPD4', False, 'itk::Point< double , 4 >'),
  ('Tile', 'itk::Tile', 'itkTile2', False, '2'),
  ('Tile', 'itk::Tile', 'itkTile3', False, '3'),
  ('Tile', 'itk::Tile', 'itkTile4', False, '4'),
  ('TileConfiguration', 'itk::TileConfiguration', 'itkTileConfiguration2', True, '2'),
  ('TileConfiguration', 'itk::TileConfiguration', 'itkTileConfiguration3', True, '3'),
  ('TileConfiguration', 'itk::TileConfiguration', 'itkTileConfiguration4', True, '4'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageISS2F', True, 'itk::Image< signed short,2 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUC2F', True, 'itk::Image< unsigned char,2 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUS2F', True, 'itk::Image< unsigned short,2 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIF2F', True, 'itk::Image< float,2 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageID2F', True, 'itk::Image< double,2 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageISS3F', True, 'itk::Image< signed short,3 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUC3F', True, 'itk::Image< unsigned char,3 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUS3F', True, 'itk::Image< unsigned short,3 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIF3F', True, 'itk::Image< float,3 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageID3F', True, 'itk::Image< double,3 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageISS4F', True, 'itk::Image< signed short,4 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUC4F', True, 'itk::Image< unsigned char,4 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIUS4F', True, 'itk::Image< unsigned short,4 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageIF4F', True, 'itk::Image< float,4 >,float'),
  ('TileMontage', 'itk::TileMontage', 'itkTileMontageID4F', True, 'itk::Image< double,4 >,float'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorISS2', True, 'itk::Image< signed short,2 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUS2', True, 'itk::Image< unsigned short,2 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIF2', True, 'itk::Image< float,2 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorID2', True, 'itk::Image< double,2 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorISS3', True, 'itk::Image< signed short,3 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUS3', True, 'itk::Image< unsigned short,3 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIF3', True, 'itk::Image< float,3 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorID3', True, 'itk::Image< double,3 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorISS4', True, 'itk::Image< signed short,4 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUC4', True, 'itk::Image< unsigned char,4 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIUS4', True, 'itk::Image< unsigned short,4 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorIF4', True, 'itk::Image< float,4 >'),
  ('NMinimaMaximaImageCalculator', 'itk::NMinimaMaximaImageCalculator', 'itkNMinimaMaximaImageCalculatorID4', True, 'itk::Image< double,4 >'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterISS2', True, 'itk::Image< signed short,2 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUC2', True, 'itk::Image< unsigned char,2 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUS2', True, 'itk::Image< unsigned short,2 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIF2', True, 'itk::Image< float,2 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterID2', True, 'itk::Image< double,2 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBUC2', True, 'itk::Image< itk::RGBPixel< unsigned char >,2 >, itk::RGBPixel<float>'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBAUC2', True, 'itk::Image< itk::RGBAPixel< unsigned char >,2 >, itk::RGBAPixel<float>'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterISS3', True, 'itk::Image< signed short,3 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUC3', True, 'itk::Image< unsigned char,3 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUS3', True, 'itk::Image< unsigned short,3 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIF3', True, 'itk::Image< float,3 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterID3', True, 'itk::Image< double,3 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBUC3', True, 'itk::Image< itk::RGBPixel< unsigned char >,3 >, itk::RGBPixel<float>'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBAUC3', True, 'itk::Image< itk::RGBAPixel< unsigned char >,3 >, itk::RGBAPixel<float>'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterISS4', True, 'itk::Image< signed short,4 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUC4', True, 'itk::Image< unsigned char,4 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIUS4', True, 'itk::Image< unsigned short,4 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIF4', True, 'itk::Image< float,4 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterID4', True, 'itk::Image< double,4 >, double'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBUC4', True, 'itk::Image< itk::RGBPixel< unsigned char >,4 >, itk::RGBPixel<float>'),
  ('TileMergeImageFilter', 'itk::TileMergeImageFilter', 'itkTileMergeImageFilterIRGBAUC4', True, 'itk::Image< itk::RGBAPixel< unsigned char >,4 >, itk::RGBAPixel<float>'),
)
factories = ()
