# This file was auto-generated by Fern from our API Definition.

import typing

PaymentMethodType = typing.Union[
    typing.AnyStr, typing.Literal["custom", "check", "bankAccount", "na", "card", "bnpl", "virtualCard", "offPlatform"]
]
