import typing
from . import Contract as Contract, PyAbi as PyAbi, PyEvm as PyEvm

def ether_to_wei(value: int) -> int: ...
def generate_random_address() -> str: ...
def create_account(evm: PyEvm, address: str = ..., value: int = ...) -> str: ...
def create_many_accounts(evm: PyEvm, num: int, value: int = ...) -> typing.List[str]: ...
def contract_from_raw_abi(evm: PyEvm, raw_abi: str) -> Contract: ...
def contract_from_abi_bytecode(evm: PyEvm, raw_abi: str, bytecode: bytes = ...) -> Contract: ...
def contract_from_inline_abi(evm: PyEvm, abi: typing.List[str]) -> Contract: ...
