# Generated by Django 3.2.20 on 2023-09-14 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230914_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 2, 20, 204526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 22, 20, 207514, tzinfo=utc)),
        ),
    ]
