# Generated by Django 3.2.20 on 2023-09-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230915_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_attempt_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
