# Generated by Django 3.2.20 on 2024-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationinvitation'),
        ('users', '0011_auto_20230923_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_to_organizations',
            field=models.ManyToManyField(blank=True, related_name='added_users', to='organizations.Organization'),
        ),
    ]
