
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-24T10:45:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ba72b0ed55c2dbff12491485ffacee7996d3490",
 "version": "0.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
