
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-25T14:27:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2134768f608632a7833f3cf3f314fe0bd1470a51",
 "version": "5.6.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
