
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-25T11:14:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "14b194fe2b1c6aae0f5785e55f2fa46b6395c3a4",
 "version": "5.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
