
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-22T12:24:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa7832b405f14b60dd70cf36b5193c5e022f418e",
 "version": "0.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
