from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Callable, Iterator, Tuple, TypeVar

ValueT = TypeVar('ValueT')
StructNested: Incomplete

def flatten_with_path_up_to(data_shallow: StructNested[Any], data_nested: StructNested[Any]) -> Tuple[Tuple[Tuple[str | int, ...], Any], ...]: ...
def flatten_with_path(data_nested: StructNested[Any]) -> Tuple[Tuple[Tuple[str | int, ...], Any], ...]: ...
def flatten_up_to(data_shallow: Any, data_nested: Any) -> Tuple[Any, ...]: ...
def flatten(data_nested: Any) -> Tuple[Any, ...]: ...
def unflatten_as(data_nested: StructNested[Any], data_leaves: Sequence | Iterator) -> StructNested[Any]: ...
def map_structure(fn: Callable, *data_nested: StructNested[Any]) -> StructNested[Any]: ...
