# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='parseservice.proto',
  package='vis.ParseService',
  serialized_pb='\n\x12parseservice.proto\x12\x10vis.ParseService\"a\n\tHumanInfo\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\x12\r\n\x05label\x18\x06 \x01(\x05\"<\n\x13ParseServiceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x16\n\tthreshold\x18\x02 \x01(\x02:\x03\x30.2\"\xff\x01\n\x14ParseServiceResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x15\n\rcontourmap_d1\x18\x02 \x01(\t\x12\x15\n\rcontourmap_d2\x18\x03 \x01(\t\x12\x15\n\rcontourmap_d3\x18\x04 \x01(\t\x12\x15\n\rcontourmap_d4\x18\x05 \x01(\t\x12\x15\n\rcontourmap_d5\x18\x06 \x01(\t\x12\x10\n\x08scoremap\x18\x07 \x01(\t\x12\x12\n\nforeground\x18\x08 \x01(\t\x12\x10\n\x08humancnt\x18\t \x01(\x05\x12.\n\thumaninfo\x18\n \x03(\x0b\x32\x1b.vis.ParseService.HumanInfoB\x03\x80\x01\x01')




_HUMANINFO = descriptor.Descriptor(
  name='HumanInfo',
  full_name='vis.ParseService.HumanInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='xmin', full_name='vis.ParseService.HumanInfo.xmin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ymin', full_name='vis.ParseService.HumanInfo.ymin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xmax', full_name='vis.ParseService.HumanInfo.xmax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ymax', full_name='vis.ParseService.HumanInfo.ymax', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='score', full_name='vis.ParseService.HumanInfo.score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='vis.ParseService.HumanInfo.label', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=137,
)


_PARSESERVICEREQUEST = descriptor.Descriptor(
  name='ParseServiceRequest',
  full_name='vis.ParseService.ParseServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='image', full_name='vis.ParseService.ParseServiceRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='threshold', full_name='vis.ParseService.ParseServiceRequest.threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=199,
)


_PARSESERVICERESPONSE = descriptor.Descriptor(
  name='ParseServiceResponse',
  full_name='vis.ParseService.ParseServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='vis.ParseService.ParseServiceResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contourmap_d1', full_name='vis.ParseService.ParseServiceResponse.contourmap_d1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contourmap_d2', full_name='vis.ParseService.ParseServiceResponse.contourmap_d2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contourmap_d3', full_name='vis.ParseService.ParseServiceResponse.contourmap_d3', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contourmap_d4', full_name='vis.ParseService.ParseServiceResponse.contourmap_d4', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contourmap_d5', full_name='vis.ParseService.ParseServiceResponse.contourmap_d5', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scoremap', full_name='vis.ParseService.ParseServiceResponse.scoremap', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='foreground', full_name='vis.ParseService.ParseServiceResponse.foreground', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='humancnt', full_name='vis.ParseService.ParseServiceResponse.humancnt', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='humaninfo', full_name='vis.ParseService.ParseServiceResponse.humaninfo', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=202,
  serialized_end=457,
)

_PARSESERVICERESPONSE.fields_by_name['humaninfo'].message_type = _HUMANINFO
DESCRIPTOR.message_types_by_name['HumanInfo'] = _HUMANINFO
DESCRIPTOR.message_types_by_name['ParseServiceRequest'] = _PARSESERVICEREQUEST
DESCRIPTOR.message_types_by_name['ParseServiceResponse'] = _PARSESERVICERESPONSE

class HumanInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HUMANINFO
  
  # @@protoc_insertion_point(class_scope:vis.ParseService.HumanInfo)

class ParseServiceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARSESERVICEREQUEST
  
  # @@protoc_insertion_point(class_scope:vis.ParseService.ParseServiceRequest)

class ParseServiceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARSESERVICERESPONSE
  
  # @@protoc_insertion_point(class_scope:vis.ParseService.ParseServiceResponse)

# @@protoc_insertion_point(module_scope)
