
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-23T19:21:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4a51b42c21f8c197f5abdf9f029320c948b5d82",
 "version": "1.24.0.post0.dev65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
