
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-24T10:58:36+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "a6a8a099d1c5020bcb2edc7edfaa2ba9bf2bc4cd",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
