# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .bank_account_update_request import BankAccountUpdateRequest
from .custom_payment_method_update_request import CustomPaymentMethodUpdateRequest
from .payment_method_base_request import PaymentMethodBaseRequest


class PaymentMethodUpdateRequest_Custom(CustomPaymentMethodUpdateRequest):
    type: typing.Literal["custom"] = "custom"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class PaymentMethodUpdateRequest_BankAccount(BankAccountUpdateRequest):
    type: typing.Literal["bankAccount"] = "bankAccount"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class PaymentMethodUpdateRequest_Card(PaymentMethodBaseRequest):
    type: typing.Literal["card"] = "card"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class PaymentMethodUpdateRequest_Check(PaymentMethodBaseRequest):
    type: typing.Literal["check"] = "check"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class PaymentMethodUpdateRequest_OffPlatform(PaymentMethodBaseRequest):
    type: typing.Literal["offPlatform"] = "offPlatform"

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


PaymentMethodUpdateRequest = typing.Union[
    PaymentMethodUpdateRequest_Custom,
    PaymentMethodUpdateRequest_BankAccount,
    PaymentMethodUpdateRequest_Card,
    PaymentMethodUpdateRequest_Check,
    PaymentMethodUpdateRequest_OffPlatform,
]
