
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-24T17:50:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "15ad5a1dfe59e76c1e0b7b10ee53f95f0ce533a4",
 "version": "2024.4.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
