# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imgfeature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10imgfeature.proto\x12\x0evis.imgfeature\"(\n\x08\x43ontSign\x12\r\n\x05sign1\x18\x01 \x01(\r\x12\r\n\x05sign2\x18\x02 \x01(\r\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"8\n\tQueryInfo\x12+\n\x05texts\x18\x01 \x03(\x0b\x32\x1c.vis.imgfeature.KeyValuePair\"\\\n\x0e\x46\x65\x61tureRequest\x12\x12\n\nquery_sign\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\'\n\x04info\x18\x03 \x01(\x0b\x32\x19.vis.imgfeature.QueryInfo\"/\n\x0b\x46\x65\x61tureData\x12\x0e\n\x06\x66\x65\x61_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66\x65\x61_data\x18\x02 \x01(\x0c\"\x80\x01\n\x0f\x46\x65\x61tureResponse\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12-\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x1b.vis.imgfeature.FeatureData\x12\x0e\n\x06\x65rr_no\x18\x04 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x05 \x01(\t\"{\n\rSimiBsRequest\x12\x12\n\nquery_sign\x18\x01 \x01(\t\x12-\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x1b.vis.imgfeature.FeatureData\x12\'\n\x04info\x18\x03 \x01(\x0b\x32\x19.vis.imgfeature.QueryInfo\"|\n\x10SimiBsResultItem\x12*\n\x08\x63ontsign\x18\x01 \x01(\x0b\x32\x18.vis.imgfeature.ContSign\x12\r\n\x05score\x18\x02 \x01(\x02\x12-\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x1b.vis.imgfeature.FeatureData\"\xcf\x01\n\x0eSimiBsResponse\x12\x0e\n\x06\x65rr_no\x18\x01 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x34\n\ndata_items\x18\x03 \x03(\x0b\x32 .vis.imgfeature.SimiBsResultItem\x12\x11\n\tcol_index\x18\x04 \x01(\x05\x12\x10\n\x08\x63ol_size\x18\x05 \x01(\x05\x12\x10\n\x08\x63ol_name\x18\x06 \x01(\t\x12/\n\x07\x63ol_res\x18\x64 \x03(\x0b\x32\x1e.vis.imgfeature.SimiBsResponse')



_CONTSIGN = DESCRIPTOR.message_types_by_name['ContSign']
_KEYVALUEPAIR = DESCRIPTOR.message_types_by_name['KeyValuePair']
_QUERYINFO = DESCRIPTOR.message_types_by_name['QueryInfo']
_FEATUREREQUEST = DESCRIPTOR.message_types_by_name['FeatureRequest']
_FEATUREDATA = DESCRIPTOR.message_types_by_name['FeatureData']
_FEATURERESPONSE = DESCRIPTOR.message_types_by_name['FeatureResponse']
_SIMIBSREQUEST = DESCRIPTOR.message_types_by_name['SimiBsRequest']
_SIMIBSRESULTITEM = DESCRIPTOR.message_types_by_name['SimiBsResultItem']
_SIMIBSRESPONSE = DESCRIPTOR.message_types_by_name['SimiBsResponse']
ContSign = _reflection.GeneratedProtocolMessageType('ContSign', (_message.Message,), {
  'DESCRIPTOR' : _CONTSIGN,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.ContSign)
  })
_sym_db.RegisterMessage(ContSign)

KeyValuePair = _reflection.GeneratedProtocolMessageType('KeyValuePair', (_message.Message,), {
  'DESCRIPTOR' : _KEYVALUEPAIR,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.KeyValuePair)
  })
_sym_db.RegisterMessage(KeyValuePair)

QueryInfo = _reflection.GeneratedProtocolMessageType('QueryInfo', (_message.Message,), {
  'DESCRIPTOR' : _QUERYINFO,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.QueryInfo)
  })
_sym_db.RegisterMessage(QueryInfo)

FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREREQUEST,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.FeatureRequest)
  })
_sym_db.RegisterMessage(FeatureRequest)

FeatureData = _reflection.GeneratedProtocolMessageType('FeatureData', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREDATA,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.FeatureData)
  })
_sym_db.RegisterMessage(FeatureData)

FeatureResponse = _reflection.GeneratedProtocolMessageType('FeatureResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEATURERESPONSE,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.FeatureResponse)
  })
_sym_db.RegisterMessage(FeatureResponse)

SimiBsRequest = _reflection.GeneratedProtocolMessageType('SimiBsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIMIBSREQUEST,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.SimiBsRequest)
  })
_sym_db.RegisterMessage(SimiBsRequest)

SimiBsResultItem = _reflection.GeneratedProtocolMessageType('SimiBsResultItem', (_message.Message,), {
  'DESCRIPTOR' : _SIMIBSRESULTITEM,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.SimiBsResultItem)
  })
_sym_db.RegisterMessage(SimiBsResultItem)

SimiBsResponse = _reflection.GeneratedProtocolMessageType('SimiBsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMIBSRESPONSE,
  '__module__' : 'imgfeature_pb2'
  # @@protoc_insertion_point(class_scope:vis.imgfeature.SimiBsResponse)
  })
_sym_db.RegisterMessage(SimiBsResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTSIGN._serialized_start=36
  _CONTSIGN._serialized_end=76
  _KEYVALUEPAIR._serialized_start=78
  _KEYVALUEPAIR._serialized_end=120
  _QUERYINFO._serialized_start=122
  _QUERYINFO._serialized_end=178
  _FEATUREREQUEST._serialized_start=180
  _FEATUREREQUEST._serialized_end=272
  _FEATUREDATA._serialized_start=274
  _FEATUREDATA._serialized_end=321
  _FEATURERESPONSE._serialized_start=324
  _FEATURERESPONSE._serialized_end=452
  _SIMIBSREQUEST._serialized_start=454
  _SIMIBSREQUEST._serialized_end=577
  _SIMIBSRESULTITEM._serialized_start=579
  _SIMIBSRESULTITEM._serialized_end=703
  _SIMIBSRESPONSE._serialized_start=706
  _SIMIBSRESPONSE._serialized_end=913
# @@protoc_insertion_point(module_scope)
