
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-22T11:08:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed133ee50080ca2301870b3afc952544a77bc28f",
 "version": "1.24.0.post0.dev43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
