# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiovemmio/mqtt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aiovemmio import pubsub_pb2 as aiovemmio_dot_pubsub__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61iovemmio/mqtt.proto\x12\x08vemmiopb\x1a\x16\x61iovemmio/pubsub.proto\"W\n\x12MQTTCommandRequest\x12)\n\x07request\x18\x01 \x01(\x0b\x32\x18.vemmiopb.CommandRequest\x12\x16\n\x0eresponse_topic\x18\x02 \x01(\tB=\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\x01Z\n./vemmiopbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiovemmio.mqtt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\001Z\n./vemmiopb'
  _MQTTCOMMANDREQUEST._serialized_start=58
  _MQTTCOMMANDREQUEST._serialized_end=145
# @@protoc_insertion_point(module_scope)
