# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aiovemmio/ultraviolet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aiovemmio import metadata_pb2 as aiovemmio_dot_metadata__pb2
from aiovemmio import units_pb2 as aiovemmio_dot_units__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61iovemmio/ultraviolet.proto\x12\x08vemmiopb\x1a\x18\x61iovemmio/metadata.proto\x1a\x15\x61iovemmio/units.proto\"C\n\x15UltravioletGetRequest\x12*\n\x08metadata\x18\x01 \x01(\x0b\x32\x18.vemmiopb.DeviceMetadata\"E\n\x16UltravioletGetResponse\x12\x1c\n\x04unit\x18\x01 \x01(\x0e\x32\x0e.vemmiopb.Unit\x12\r\n\x05value\x18\x02 \x01(\x01\"@\n\x11UltravioletReport\x12\x1c\n\x04unit\x18\x01 \x01(\x0e\x32\x0e.vemmiopb.Unit\x12\r\n\x05value\x18\x02 \x01(\x01\x32i\n\x12UltravioletService\x12S\n\x0eUltravioletGet\x12\x1f.vemmiopb.UltravioletGetRequest\x1a .vemmiopb.UltravioletGetResponseB=\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\x01Z\n./vemmiopbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aiovemmio.ultraviolet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\001Z\n./vemmiopb'
  _ULTRAVIOLETGETREQUEST._serialized_start=90
  _ULTRAVIOLETGETREQUEST._serialized_end=157
  _ULTRAVIOLETGETRESPONSE._serialized_start=159
  _ULTRAVIOLETGETRESPONSE._serialized_end=228
  _ULTRAVIOLETREPORT._serialized_start=230
  _ULTRAVIOLETREPORT._serialized_end=294
  _ULTRAVIOLETSERVICE._serialized_start=296
  _ULTRAVIOLETSERVICE._serialized_end=401
# @@protoc_insertion_point(module_scope)
