# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account_created', 'Account Created')], max_length=32)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Notification Template',
            },
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('type', 'is_active')]),
        ),
    ]
