"""Caching utilities."""
from __future__ import annotations

from typing import Any, Callable

class cachedproperty:
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Any = None) -> Any: ...
    def __init__(self, func: Callable[[Any], Any], doc: str | None = None) -> None: ...
    def __repr__(self) -> str: ...
