# - bundle_report()
# - create_bundle(bundle_data)
# - delete_bundle(bundle_id)
# - list_bundles()
# - modify_bundle(bundle_id, **kwargs)
# - read_bundle(bundle_id)
# - bundleless_promotion()
# - cancel_scheduled_bundle_promotion(promotion_id)
# - delete_scheduled_bundle_promotion(promotion_id)
# - promote_bundle_or_schedule_bundle_promotion(bundle_id, promotion_data)
# - create_promotion_target(target_data)
# - modify_promotion_target(target_id, **kwargs)
# - list_promotion_targets()
# - delete_promotion_target(target_id)
# - read_promotion_target(target_id)
# - refresh_target_agents(target_id)