# - create_universal_template(template_data)
# - delete_universal_template(template_id)
# - list_universal_templates()
# - modify_universal_template(template_id, **kwargs)
# - read_universal_template(template_id)
# - restore_default_universal_template_icon(template_id)
# - set_universal_template_icon(template_id, icon_data)
# - universal_template_delete_extension_archive(template_id)
# - universal_template_download_extension_archive(template_id)
# - universal_template_upload_extension_archive(template_id, file_data)
# - universal_template_export(template_id)
# - universal_template_import(file_data)