# - assign_execution_user_to_webhook(webhook_id, execution_user)
# - disable_webhook(webhook_id)
# - enable_webhook(webhook_id)
# - enable_disable_multiple_webhooks(webhook_ids, enable=True)
# - list_webhooks()
# - modify_webhooks(webhook_id, **kwargs)
# - read_webhook(webhook_id)
# - register_webhook(webhook_data)
# - unassign_execution_user_from_webhook(webhook_id)
# - unregister_webhook(webhook_id)