
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-23T14:59:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "12ac7c9214771d576db8aaf0d0d9bb9d96c6e4f4",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
