
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-21T02:13:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d487995c8f685729ee5e1259f364034dab4811da",
 "version": "1.4.dev2416"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
