
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-31T22:51:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "640afd5bacc1a42f1e3c55c266fc5a02f668b2d1",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
