# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .filter_label_equal import FilterLabelEqual
from .filter_label_is_not_null import FilterLabelIsNotNull
from .filter_label_is_null import FilterLabelIsNull
from .filter_label_not_equal import FilterLabelNotEqual


class FilterLabel_Equal(FilterLabelEqual):
    operator: typing.Literal["EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterLabel_IsNotNull(FilterLabelIsNotNull):
    operator: typing.Literal["IS_NOT_NULL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterLabel_IsNull(FilterLabelIsNull):
    operator: typing.Literal["IS_NULL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class FilterLabel_NotEqual(FilterLabelNotEqual):
    operator: typing.Literal["NOT_EQUAL"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


FilterLabel = typing.Union[FilterLabel_Equal, FilterLabel_IsNotNull, FilterLabel_IsNull, FilterLabel_NotEqual]
