from _pytest.config import Config as Config
from _typeshed import Incomplete as Incomplete
from pathlib import Path

logger: Incomplete

def pytest_addoption(parser) -> None: ...
def pytest_addhooks(pluginmanager) -> None: ...
def pytest_configure(config: Config): ...
def pytest_collect_file(parent, file_path: Path): ...
def async_feedback(**kwargs) -> None: ...
