from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    meta_column_name: str

class ProxySettings:
    def __init__(self) -> None: ...
    def __getattr__(self, item) -> None: ...
    def __setattr__(self, key, value) -> None: ...
    def reload_settings(self, d) -> None: ...

settings: Settings
