"""Provide the InboxableMixin class."""

class InboxableMixin:
    async def block(self) -> None: ...
    async def collapse(self) -> None: ...
    async def mark_read(self) -> None: ...
    async def mark_unread(self) -> None: ...
    async def unblock_subreddit(self) -> None: ...
    async def uncollapse(self) -> None: ...
