import pathlib

APP_DIR = pathlib.Path.home() / ".iap_cli"
# CONFIG_FILENAME = "config.toml"
# CONFIG_FILEPATH = APP_DIR / CONFIG_FILENAME
CREDENTIALS_FILENAME = ".env"
CREDENTIALS_FILEPATH = APP_DIR / CREDENTIALS_FILENAME
INVENTORY_FILENAME = "inventory.json"
INVENTORY_FILEPATH = APP_DIR / INVENTORY_FILENAME
